### PR TITLE
fixes pep8 warning : ignores E501

### PR DESCRIPTION
**Pull request by taranjeet**
This PR fixes pep8 warnings in the project. Ignored E501 as the max-length needs to be decided. I was thinking of keeping it 80. Let me know what suits your requirement.

### CODE REVIEW

**Comment by ryanmcdermott** [comment]
Thanks for helping out and fixing those warnings!

**Comment by taranjeet** [comment]
Sure, These days I am keeping an eye on this only.

**Comment by taranjeet** [comment]
Btw, what is your preferred column width? Now only E501 warnings are left in the project. I was thinking of 80, but let me know your preference.

**Comment by ryanmcdermott** [comment]
Awesome! I prefer 80. If there are some lines that go over that then they are definitely requiring a fix.

**Pull request merged**
